blank_issues_enabled: false
contact_links:
  - name: "Report a Direct Heresy"
    url: "https://github.com/Pascal-the-dog/CHIM-speak"
    about: "If your soul is too weak to use the automated issue tracking arrays."
